baseURL = "https://faranakrajabi.com" 
title = "Faranak Rajabi" 
theme = "hugo-theme-m10c" 

[params] 
author = "Faranak Rajabi" 
description = "Computational Science and Engineering Researcher" 

[params.style] 
darkestColor = "#212121" 
darkColor = "#212121" 
lightColor = "#f5e3e0" 
lightestColor = "#f5f5f5" 
primaryColor = "#ffffff" 

[[params.social]] 
icon = "brand-github" 
name = "Github" 
url = "https://github.com/faranakR" 

[[params.social]] 
icon = "brand-linkedin" 
name = "LinkedIn" 
url = "https://www.linkedin.com/in/faranak-rajabi" 

[[params.social]] 
icon = "academic"  # icon for Google Scholar, may vary by theme
name = "Google Scholar" 
url = "https://scholar.google.com/citations?user=faranakrajabi"

[[params.social]] 
icon = "researchgate"  # ResearchGate may need a custom icon depending on the theme
name = "ResearchGate" 
url = "https://www.researchgate.net/profile/Faranak-Rajabi"
